require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
-- require "user.lualine"
-- require "user.lualine-update"
-- require "user.lualine-new"
-- require "user.ui.tabby"
-- require "user.ui.colors"
-- require "user.ui.feline"
require "user.feline"
-- require "user.slanted_gaps"
-- require "user.evil_lualine"
-- require "user.diffview"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
