require "user.options"
require "user.keymaps"
require "user.plugins"
-- require "user.spaceduck"
require "user.tokyonight"
require "user.colorscheme"

require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
-- require "user.nvim-tree"
require "user.nvim-tree-revamp"
require "user.bufferline"
require "user.lualine"
-- require "user.slanted_gaps"
-- require "user.diffview"
-- require "user.evil_lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
