--[[ require "user.tokyonight" ]]
require "user.ui.nightfox"
--[[ require "user.ui.pinkmare" ]]
--[[ require "user.ui.onedark" ]]
--[[ require "user.ui.solarized" ]]
--[[ require "user.ui.dracula" ]]
--[[ require "user.ui.github-theme" ]]
--[[ require "user.ui.gruvbox" ]]
--[[ require "user.ui.spaceduck" ]]


-- vim.cmd [[
-- try
--   " colorscheme darkplus
--
--   " ---------------- Spaceduck --------------------
--   " if exists('+termguicolors')
--   "   let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
--   "   let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
--   "   set termguicolors
--   " endif
--   " colorscheme spaceduck
--
--   " ------------- Gruvbox ----------------
--   " set background=dark
--   " colorscheme gruvbox
--
--   " ------------- nightfox ----------------
--   " colorscheme nightfox
--   " colorscheme duskfox
--
--   " ------------- tokyonight ----------------
--   " set background=dark
--   " colorscheme tokyonight
--
--   " ------------- papercolor light ----------------
--   " config for PaperColor
--   " set t_Co=256   " This is may or may not needed.
--   " set background=light
--   " colorscheme PaperColor
--
--   " ------------- papercolor dark ----------------
--   " set t_Co=256   " This is may or may not needed.
--   " set background=dark
--   " colorscheme PaperColor
--
--   " ------------- Onedark ----------------
--   " colorscheme onedark
--
--   " ------------- PinkMare ----------------
--   " colorscheme pinkmare
--
--
-- catch /^Vim\%((\a\+)\)\=:E185/
--   colorscheme default
--   set background=dark
-- endtry
-- ]]
